#!/bin/sh
# Combine all status bar scripts
battery=$(~/.local/bin/statusbar/sb-battery)
cpu=$(~/.local/bin/statusbar/sb-cpu)
disk=$(~/.local/bin/statusbar/sb-disk)
ram=$(~/.local/bin/statusbar/sb-ram)
uptime=$(~/.local/bin/statusbar/sb-uptime)
volume=$(~/.local/bin/statusbar/sb-volume)
weather=$(~/.local/bin/statusbar/sb-weather)
wifi=$(~/.local/bin/statusbar/sb-wifi)
words=$(~/.local/bin/statusbar/sb-words)

# Output the combined status
echo "$words | $weather | $cpu | $ram | $disk | $wifi | $volume | $battery | $uptime"
