#!/bin/bash
# Check If You Are Connected To Inetenet.
if ! curl -s https://google.com &>/dev/null; then
    echo "Can't Fetch"
    exit 1;
fi 
# Fetch weather information from wttr.in
weather=$(curl -s wttr.in/Zanjan?format=3)
# # Output the weather information
echo "$weather"
